#!/usr/bin/env bash

set -e

DEFAULT_TITLE="Alarm!"
time="$1"
DEFAULT_MSG=${2:-'\\n!!!'}
CURRENT_UNIX_TIME=$(date +"%s")

function convert_time_to_sec() {
  local target_unix_time
  target_unix_time=$(date -d "$1" +"%s")
  echo $(($target_unix_time - $CURRENT_UNIX_TIME))
}

function convert_sec_to_sec() {
  local date_command_format=$(echo $1 | sed "s/s/ second/g")
  convert_time_to_sec "$date_command_format"
}

function convert_min_to_sec() {
  local date_command_format=$(echo $1 | sed "s/m/ minute/g")
  convert_time_to_sec "$date_command_format"
}

function convert_hour_to_sec() {
  local date_command_format=$(echo $1 | sed "s/h/ hour/g")
  convert_time_to_sec "$date_command_format"
}

function convert_datetime_from_unix_time() {
  date +"%Y/%m/%d %H:%M:%S" -d "@$(($CURRENT_UNIX_TIME + $1))"
}

if [[ $time == *:* ]]; then
  SEC=$(convert_time_to_sec $time)
elif [[ $time == *s ]]; then
  SEC=$(convert_sec_to_sec $time)
elif [[ $time == *m ]]; then
  SEC=$(convert_min_to_sec $time)
elif [[ $time == *h ]]; then
  SEC=$(convert_hour_to_sec $time)
else
  SEC=$time
fi

echo "alert after $SEC sec [$(convert_datetime_from_unix_time "$SEC")]"

function send_notification() {
  local title="$1"
  local msg="$2"
  # WSL: use PowerShell to pop a Windows toast notification
  if [[ -f /proc/sys/fs/binfmt_misc/WSLInterop ]] && command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -Command "
      Add-Type -AssemblyName System.Windows.Forms
      \$n = New-Object System.Windows.Forms.NotifyIcon
      \$n.Icon = [System.Drawing.SystemIcons]::Information
      \$n.Visible = \$true
      \$n.ShowBalloonTip(5000, '$title', '$msg', [System.Windows.Forms.ToolTipIcon]::Warning)
      Start-Sleep -Milliseconds 5500
      \$n.Dispose()
    " >/dev/null 2>&1
    return
  fi
  # Bare metal: use notify-send if available
  if command -v notify-send >/dev/null 2>&1; then
    notify-send "$title" "$msg" -u critical
    return
  fi
  # Universal fallback: terminal bell + printed message
  printf '\a%s: %s\n' "$title" "$msg" >/dev/tty 2>/dev/null || true
}

nohup bash -c "$(declare -f send_notification); sleep $SEC && send_notification '$DEFAULT_TITLE' '$DEFAULT_MSG'" >/dev/null 2>&1 &
